#!/bin/bash
function killservice()
{   
    pgrep -x $1 > /dev/null 
    if [ $? -eq 0 ]
    then
        killall -9 -q $1 & > /dev/null
    fi
}

killall psme-rest-server > /dev/null
killall psme-chassis > /dev/null
killservice 'psme-rest-server';
killservice 'psme-chassis';
service psme stop

if [ -f /etc/psme/platform_info.conf ];then
    rm /etc/psme/platform_info.conf 
fi

if [ -f /etc/psme/service_uuid.json ];then
    rm /etc/psme/service_uuid.json
fi

